dependencies:
  - streamlit
  - pandas
  - matplotlib
  - numpy
  - pydeck
  - joblib
  - xgboost
  - biopython
  - ete3
  - pip
  - xgboost
  - scikit-learn
  - fasttree
  - mafft
  - matplotlib.pyplot
  - conda-forge::conda_subprocess